FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
COPY server/package*.json ./server/
COPY shared/package*.json ./shared/

RUN npm install

COPY . .

WORKDIR /app/server

EXPOSE 3001

CMD ["npm", "run", "dev"]
